name: maya-unit-testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  maya-linux:
    runs-on: ubuntu-latest
  strategy:
    fail-fast: false
    matrix:
      include:
        - image: "2017"
          pip: "2.7/get-pip.py"
        - image: "2018"
          pip: "2.7/get-pip.py"
        - image: "2019"
          pip: "2.7/get-pip.py"
        - image: "2020"
          pip: "2.7/get-pip.py"
        - image: "2022"
          pip: "get-pip.py"

  container: mottosso/maya:${{ matrix.image }}

  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Environment
      run: |
        wget https://bootstrap.pypa.io/pip/${{ matrix.pip }}
        mayapy get-pip.py --user
        mayapy -m pip install --user numpy scipy
    - name: Tests
      run: |
        export PYTHONPATH=$(pwd)/scripts
        mayapy ./tests/bin/run.py
